export const Data = [
  {
    id: 1,
    month: "Jan",
    declined: 4,
    pending: 4,
    scheduled: 6,
  },
  { id: 1, month: "Feb", declined: 2, pending: 5, scheduled: 9 },
  {
    id: 1,
    month: "Mar",
    declined: 4,
    pending: 4,
    scheduled: 6,
  },
  { id: 1, month: "Apr", declined: 2, pending: 5, scheduled: 9 },
  {
    id: 1,
    month: "May",
    declined: 4,
    pending: 4,
    scheduled: 6,
  },
  { id: 1, month: "Jun", declined: 2, pending: 5, scheduled: 9 },
  {
    id: 1,
    month: "Jul",
    declined: 4,
    pending: 4,
    scheduled: 6,
  },
  { id: 1, month: "Aug", declined: 2, pending: 5, scheduled: 9 },
  {
    id: 1,
    month: "Spe",
    declined: 4,
    pending: 4,
    scheduled: 6,
  },
  { id: 1, month: "Oct", declined: 2, pending: 5, scheduled: 9 },
  {
    id: 1,
    month: "Nov",
    declined: 4,
    pending: 4,
    scheduled: 6,
  },
  { id: 1, month: "Dec", declined: 2, pending: 5, scheduled: 9 },
  
];
